export { default as AddStudent } from './AddStudent';
export { default as StudentList } from './StudentList';
export {default as MainPage} from './MainPage';
export {default as LandingPage} from './LandingPage';
export {default as Login } from "./Login";
export {default as Register} from "./Register";
export {default as Map} from './Map';
export {default as StudentDashboard} from './StudentDashboard';
export {default as Class} from './Class';
export {default as TeacherDashboard} from './TeacherDashboard';
export {default as ClassDetail} from './ClassDetail';
export {default as CourseRegister} from './CourseRegister';
export {default as StudentDetail} from './StudentDetail';
export {default as ClassGrade} from './ClassGrade';
export {default as StudentGrade} from './StudentGrade';
export {default as EditGradeModal} from './EditGradeModal';